backend:
  name: github
  repo: rambros3d/rambrospcb
  branch: main
  base_url: https://sveltia-cms-auth.rambrosteam.workers.dev

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "beginner"
    label: "Beginner Tutorials"
    folder: "content/beginner"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Template", name: "template", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Weight", name: "weight", widget: "number", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "intermediate"
    label: "Intermediate Tutorials"
    folder: "content/intermediate"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Template", name: "template", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Weight", name: "weight", widget: "number", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "resources"
    label: "Resources"
    folder: "content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Template", name: "template", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Weight", name: "weight", widget: "number", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
