backend:
  name: github
  repo: rambros3d/rambrospcb
  branch: main
  base_url: https://sveltia-cms-auth.rambrosteam.workers.dev

output:
  omit_empty_optional_fields: true

slug:
  encoding: ascii
  clean_accents: true

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "content/_index.md"
        format: toml-frontmatter
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "beginner"
    label: "Beginner Tutorials"
    folder: "content/beginner"
    create: true
    delete: false
    format: toml-frontmatter
    exclude: ["_index.md"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Template", name: "template", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss", picker_utc: false, required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Weight", name: "weight", widget: "number", value_type: "int/string", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "beginner-index"
    label: "Beginner Section Index"
    files:
      - name: "beginner-index"
        label: "Beginner Section Index"
        file: "content/beginner/_index.md"
        format: toml-frontmatter
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "intermediate"
    label: "Intermediate Tutorials"
    folder: "content/intermediate"
    create: true
    delete: false
    format: toml-frontmatter
    exclude: ["_index.md"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Template", name: "template", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss", picker_utc: false, required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Weight", name: "weight", widget: "number", value_type: "int/string", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "intermediate-index"
    label: "Intermediate Section Index"
    files:
      - name: "intermediate-index"
        label: "Intermediate Section Index"
        file: "content/intermediate/_index.md"
        format: toml-frontmatter
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Template", name: "template", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "resources"
    label: "Resources"
    folder: "content/resources"
    create: true
    delete: false
    format: toml-frontmatter
    exclude: ["_index.md"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Template", name: "template", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss", picker_utc: false, required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Weight", name: "weight", widget: "number", value_type: "int/string", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "resources-index"
    label: "Resources Section Index"
    files:
      - name: "resources-index"
        label: "Resources Section Index"
        file: "content/resources/_index.md"
        format: toml-frontmatter
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown", required: false }
